default: &default
  adapter: mysql2
  reconnect: true
  encoding: utf8
  username: abdul
  password: bukalapak
  pool: 3     
  timeout:  10
  host:     127.0.0.1
  port:     3306

development:
  <<: *default
  database: halohalo_development

test: &test
  <<: *default
  database:   halohalo_test

production:
  <<: *default
  database: halohalo

staging:
  <<: *default
  database: halohalo_staging
